# Site settings
title: sepulchered
description: > # this means to ignore newlines until "baseurl:"
  Trying to get into everything I'm interested in... devops, design, linguistics, engineering, art and music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: //andrey.dresvyannikov.ru # the base hostname & protocol for your site

owner:
  name: Andrey Dresvyannikov
  email: andrey@dresvyannikov.ru
  twitter: dresvyannikov_a
  facebook: dresvyannikov.a
  github:  sepulchered
  stackexchange: sepulchered
  linkedin: andrey-dresvyannikov
  instagram: dresvyannikov_a
  google_plus: +AndreyDresvyannikov

timezone: Europe/Moscow
future: true
disqus_shortname: andreydresvyannikovru
google_analytics: UA-38597125-3
highlighter: pygments
# Build settings
markdown: kramdown

karmdown:
  input: GFM

paginate: 5
